回退 'Pull Request !35 : 避免在arm上 configure without-isal 冲突'

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -514,11 +514,9 @@ if [[ "${CONFIG[ISAL]}" = "y" ]]; then
 	fi
 fi
 
-if [[ $arch == x86_64* ]]; then
-	if [[ "${CONFIG[ISAL]}" = "n" ]] && [[ "${CONFIG[REDUCE]}" = "y" ]]; then
-			echo "ERROR Conflicting options: --with-reduce is not compatible with --without-isal."
-			exit 1
-	fi
+if [[ "${CONFIG[ISAL]}" = "n" ]] && [[ "${CONFIG[REDUCE]}" = "y" ]]; then
+		echo "ERROR Conflicting options: --with-reduce is not compatible with --without-isal."
+		exit 1
 fi
 
 if [ -z "${CONFIG[ENV]}" ]; then
