avoid without-isal conflict （cherry picked commit from <gitee.com//kunpeng_compute/spdk/commit/d3f90c54df4f11d66722d4aee061020b92740a5f>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -514,9 +514,11 @@ if [[ "${CONFIG[ISAL]}" = "y" ]]; then
 	fi
 fi
 
-if [[ "${CONFIG[ISAL]}" = "n" ]] && [[ "${CONFIG[REDUCE]}" = "y" ]]; then
-		echo "ERROR Conflicting options: --with-reduce is not compatible with --without-isal."
-		exit 1
+if [[ $arch == x86_64* ]]; then
+	if [[ "${CONFIG[ISAL]}" = "n" ]] && [[ "${CONFIG[REDUCE]}" = "y" ]]; then
+			echo "ERROR Conflicting options: --with-reduce is not compatible with --without-isal."
+			exit 1
+	fi
 fi
 
 if [ -z "${CONFIG[ENV]}" ]; then
